Blog/Blog/urls.py
import xadmin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views
from django.urls import path, include, re_path
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

from Blog.autocomplete import CategoryAutoComplete, TagAutoComplete
from Blog.custom_site import custom_site
from blogApp.apis import PostViewSet, CategoryViewSet, TagViewSet
from blogApp.rss import LatestPostFeed
from blogApp.sitemap import PostSitemap
from comment.apis import CommentViewSet
from config.apis import LinkViewSet, SideBarViewSet

router = DefaultRouter()
router.register(r'post', PostViewSet, basename='api-post')
router.register(r'category', CategoryViewSet, basename='api-category')
router.register(r'tag', TagViewSet, basename='api-tag')
router.register(r'comment', CommentViewSet, basename='api-comment')
router.register(r'link', LinkViewSet, basename='api-link')
router.register(r'sidebar', SideBarViewSet, basename='api-sidebar')


urlpatterns = [
    path('admin/', custom_site.urls),
    path('super_admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls, name='xadmin'),
    path('config/', include('config.urls', namespace='config')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('rss/', LatestPostFeed(), name='rss'),
    path('sitemap.xml/', sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),
    path('category-autocomplete/', CategoryAutoComplete.as_view(), name='category-autocomplete'),
    path('tag-autocomplete/', TagAutoComplete.as_view(), name='tag-autocomplete'),
    path('api/', include((router.urls, 'api'))),
    path('api/docs/', get_schema_view(title='My Project')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^', include('blogApp.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk')), ]

Blog/blogApp/urls.py
#!/user/bin/env python
# 每天都要有好心情
from django.urls import path, re_path

from blogApp import views

app_name = 'blog'

urlpatterns = [
    path('category/<int:category_id>/', views.CategoryView.as_view(), name='category-list'),
    path('tag/<int:tag_id>/', views.TagView.as_view(), name='tag-list'),
    path('post/<int:post_id>.html', views.PostDetailView.as_view(), name='post-detail'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('author/<int:owner_id>/', views.AuthorView.as_view(), name='author'),
    re_path(r'^$', views.IndexView.as_view(), name='post_list'),
]

Blog/templates/themes/bootstrap/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}
        首页
    {% endblock %}-友利奈绪</title>
    {% block extra_head %}
    {% endblock %}
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.0/css/bootstrap.css" rel="stylesheet">
    <style>
        .post {
            margin-bottom: 0.3125rem;
        }
    </style>
</head>
<body>
<div class="container head">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">首页</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% for cate in navs %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:category-list' cate.id %}">{{ cate.name }}</a>
                </li>
            {% endfor %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:search' %}">
            <input class="form-control mr-sm-2" type="search" name="keyword" placeholder="Search" aria-label="Search" value="{{ keyword }}">
            <button class="btn btn-outline-success" type="submit">搜索</button>
        </form>
    </div>
    </nav>
    <div class="jumbotron">
        <h1 class="display-4">明日方舟</h1>
        <p class="lead">基于Django的多人博客系统</p>
    </div>
</div>

<div class="container main">
    <div class="row">
        <div class="col-9 post-list">
            {% block main %}
            {% endblock %}
        </div>
        <div class="col-3">
            {% block sidebar %}
                {% for sidebar in sidebars %}
                    <div class="card sidebar">
                        <div class="card-body">
                            <h4 class="card-title">{{ sidebar.title }}</h4>
                            <p>
                                {{ sidebar.content_html }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>

<footer class="footer">
    {% block footer %}
    <div class="container">
        <hr>
        <nav class="nav category">
            {% for cate in normal %}
                <a class="nav-link" href="{% url 'blog:category-list' cate.id %}">{{ cate.name }}</a>
            {% endfor %}
        </nav>
    </div>
    <div class="container power">
        <span class="text-muted">Power by 友利奈绪@ylnx</span>
    </div>
    {% endblock %}
</footer>
</body>
</html>

Blog/templates/themes/bootstrap/blog/detail.html
{% extends 'blog/base.html' %}
{% load comment_block %}
{% block title %}
    {{ post.title }}--友利奈绪
{% endblock %}
{% block extra_head %}
    <link rel="stylesheet" href="https://cdn.bootcss.com/highlight.js/9.18.1/styles/googlecode.min.css">
    <script src="https://cdn.bootcss.com/highlight.js/9.18.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
{% endblock %}
{% block main %}
    {% if post %}
        <h1>{{ post.title }}</h1>
        <div>
            <span>作者:{{ post.owner.username }}</span>
            <span>分类:{{ post.category.name }}</span>
        </div>
        <hr>
        <p>
            {% autoescape off %}
                {{ post.content_html }}
            {% endautoescape %}
        </p>
    {% endif %}
    {% comment_block request.path %}
{% endblock %}

Blog/templates/themes/bootstrap/blog/list.html
{% extends 'blog/base.html' %}

{% block title %}
    {% if tag %}
        标签页: {{ tag.name }}
    {% elif category %}
        分类页: {{ category.name }}
    {% else %}
        首页
    {% endif %}
{% endblock %}

{% block main %}
    {% for post in post_lists %}
        <div class="card post">
            <h5 class="card-title"><a href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h5>
            <span class="card-link">作者: <a href="{% url 'blog:author' post.owner.id %}">{{ post.owner.username }}</a></span>
            <span class="card-link">分类: <a href="{% url 'blog:category-list' post.category.id %}">{{ post.category.name }}</a></span>
            <span class="card-link">标签:
								{% for tag in post.tag.all %}
                                    <a href="{% url 'blog:tag-list' tag.id %}">{{ tag.name }}</a>
								{% endfor %}
							</span>
            <p class="card-text">{{ post.desc }} <a href="{% url 'blog:post-detail' post.id %}">完整内容</a></p>
        </div>
    {% endfor %}
    {% if page_obj %}
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
    {% endif %}
{% endblock %}