Blog/Blog/urls.py
import xadmin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views
from django.urls import path, include, re_path
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

from Blog.autocomplete import CategoryAutoComplete, TagAutoComplete
from Blog.custom_site import custom_site
from blogApp.apis import PostViewSet, CategoryViewSet, TagViewSet
from blogApp.rss import LatestPostFeed
from blogApp.sitemap import PostSitemap
from comment.apis import CommentViewSet
from config.apis import LinkViewSet, SideBarViewSet

router = DefaultRouter()
router.register(r'post', PostViewSet, basename='api-post')
router.register(r'category', CategoryViewSet, basename='api-category')
router.register(r'tag', TagViewSet, basename='api-tag')
router.register(r'comment', CommentViewSet, basename='api-comment')
router.register(r'link', LinkViewSet, basename='api-link')
router.register(r'sidebar', SideBarViewSet, basename='api-sidebar')


urlpatterns = [
    path('admin/', custom_site.urls),
    path('super_admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls, name='xadmin'),
    path('config/', include('config.urls', namespace='config')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('rss/', LatestPostFeed(), name='rss'),
    path('sitemap.xml/', sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),
    path('category-autocomplete/', CategoryAutoComplete.as_view(), name='category-autocomplete'),
    path('tag-autocomplete/', TagAutoComplete.as_view(), name='tag-autocomplete'),
    path('api/', include((router.urls, 'api'))),
    path('api/docs/', get_schema_view(title='My Project')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^', include('blogApp.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk')), ]

Blog/comment/urls.py
#!/user/bin/env python
# 每天都要有好心情
from django.urls import path

from comment import views

app_name = 'comment'

urlpatterns = [
    path('', views.CommentView.as_view(), name='commentView'),
]

Blog/comment/models.py
from django.db import models

from blogApp.models import Post


class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    target = models.CharField(max_length=100, verbose_name='评论目标')
    content = models.CharField(max_length=2000, verbose_name='内容')
    nickname = models.CharField(max_length=50, verbose_name='昵称')
    website = models.URLField(verbose_name='网站')
    email = models.EmailField(verbose_name='邮箱')
    status = models.PositiveIntegerField(default=STATUS_NORMAL,
                                         choices=STATUS_ITEMS, verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '评论'

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

Blog/comment/forms.py
#!/user/bin/env python
# 每天都要有好心情
import mistune
from django import forms

from comment.models import Comment


class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={
                'class': 'form-control',
                'style': 'width: 60%;',
            }
        )
    )
    email = forms.CharField(
        label='Email',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={
                'class': 'form-control',
                'style': 'width: 60%;',
            }
        )
    )
    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={
                'class': 'form-control',
                'style': 'width: 60%;',
            }
        )
    )

    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 6,
                'cols': 60,
            }
        )
    )

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 10:
            raise forms.ValidationError('太短啦!就这?')
        content = mistune.markdown(content)
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

Blog/comment/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from comment.forms import CommentForm


class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            succeed = True
            return redirect(target)
        else:
            succeed = False

        context = {
            'succeed': succeed,
            'form': comment_form,
            'target': target,
        }
        return self.render_to_response(context)

Blog/templates/themes/bootstrap/comment/block.html
<hr>
<div class="comment">
    <ul>
        {% for comment in comment_list %}
            <li class="list-group-item">
                <div class="nickname">
                    <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                    <span>{{ comment.created_time }}</span>
                </div>
                <div class="comment-content">
                    {% autoescape off %}
                        {{ comment.content }}
                    {% endautoescape %}
                </div>
            </li>
        {% endfor %}
    </ul>
    <hr>
    <form action="{% url 'comment:commentView' %}" method="post" class="form-group">
        {% csrf_token %}
        <input type="hidden" name="target" value="{{ target }}">
        {{ comment_form }}
        <input type="submit" value="写好了!">
    </form>
</div>

Blog/templates/themes/bootstrap/comment/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论结果页</title>
</head>
<body>
    <div class="result">
        {% if succeed %}
            评论成功!
            <a href="{{ target }}">返回</a>
        {% else %}
            <ul class="errorlist">
                {% for field, message in form.errors.items %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
            <a href="javascript:window.history.back();">返回</a>
        {% endif %}
    </div>
</body>
</html>